server {
    listen 80;
    root /var/www/html;

    index index.php index.html;

    # Aumenta el límite de subida a 128M (puedes poner más si quieres)
    client_max_body_size 128M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_read_timeout 900;  # aumenta a 5 minutos
    }
}
